version: '3.9'
services:
  api:
    build:
      context: .
      target: development
    container_name: temtem-api
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://${MONGO_CONTAINER}:27017/${MONGO_DB}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: ${MONGO_CONTAINER}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
